server:
    context-path: /meetingSign
    port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/meetingsign?useUnicode=true&characterEncoding=utf8
    username:  ****
    password:  ****
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  redis:
    host: ****
    port:  ****
wechat:
   mpAppId:  ****
   mpAppSecret: ****
meetingSignUrl:
   meeting:  ****
